name: Run Test

on:
  pull_request:
    branches: dev

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tutorial_7
    steps:
      - name: CheckOut Your Code
        uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Run teacher tests
        run: python -m unittest discover -v -p "test_*_teacher.py"
